### ISSUE TITLE
请恕在下无能=。=

### ISSUE THREAD

**Issue by neodreamtale** [ryanhoo/Zhihu-Parallax-Animation#3]
不好意思，这个项目导入之后，依赖包老是找不到。
build.gradle中写的是    compile project(':library')
但是这个library在./Android-ViewPagerIndicator/library。
怎么配置才能找到这个库呢？

**Comment by ryanhoo** [comment]
Sorry it's not your fault. 

It uses git submodule to reference viewpagerindicator as library. Because viewpagerindicator didn't support gradle when I started this project. So if you want to compile this project then you have to know how to init a git submodule based project.
I will give you a hint:
`git submodule init` or `git submodule update --init`
But I think you'd better to know what is git submodule and why you need to do this.
